### ISSUE TITLE
PDF generation is has some problem

### ISSUE THREAD

**Issue by naveenpf** [hotosm/gpsdd-documentation#4]
1. SDG goals are not coming in order

**Comment by naveenpf** [comment]
@russbiggs Can you please help ?

**Comment by russbiggs** [comment]
This is probably because the content is being sorted by title, causing the 1, 11, 12, 13 etc. order.  I believe using the ```weight``` field in the markdown front matter resolves this

**Comment by naveenpf** [comment]
@russbiggs weight applies to html. it is rendering properly. pdf ordering is completely gone.
